<?php

use Illuminate\Database\Seeder;
use App\Profissao;

class ProfissaoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Profissao::create(['id' => '101', 'nome' => 'Oficiais generais das forças armadas']);
        Profissao::create(['id' => '102', 'nome' => 'Oficiais das forças armadas']);
        Profissao::create(['id' => '103', 'nome' => 'Praças das forças armadas']);
        Profissao::create(['id' => '201', 'nome' => 'Oficiais superiores da polícia militar']);
        Profissao::create(['id' => '202', 'nome' => 'Capitães da  polícia militar']);
        Profissao::create(['id' => '203', 'nome' => 'Tenentes da polícia militar']);
        Profissao::create(['id' => '211', 'nome' => 'Subtenentes e sargentos da policia militar']);
        Profissao::create(['id' => '212', 'nome' => 'Cabos e soldados da polícia militar']);
        Profissao::create(['id' => '301', 'nome' => 'Oficiais superiores do corpo de bombeiros militar']);
        Profissao::create(['id' => '302', 'nome' => 'Oficiais intermediários do corpo de bombeiros militar']);
        Profissao::create(['id' => '303', 'nome' => 'Tenentes do corpo de bombeiros militar']);
        Profissao::create(['id' => '311', 'nome' => 'Subtenentes e sargentos do corpo de bombeiros militar']);
        Profissao::create(['id' => '312', 'nome' => 'Cabos e soldados do corpo de bombeiros militar']);
        Profissao::create(['id' => '1111', 'nome' => 'Legisladores']);
        Profissao::create(['id' => '1112', 'nome' => 'Dirigentes gerais da administração pública']);
        Profissao::create(['id' => '1113', 'nome' => 'Magistrados']);
        Profissao::create(['id' => '1114', 'nome' => 'Dirigentes do serviço público']);
        Profissao::create(['id' => '1115', 'nome' => 'Gestores públicos']);
        Profissao::create(['id' => '1130', 'nome' => 'Dirigentes de povos indígenas, de quilombolas e caiçaras']);
        Profissao::create(['id' => '1141', 'nome' => 'Dirigentes de partidos políticos']);
        Profissao::create(['id' => '1142', 'nome' => 'Dirigentes e administradores de entidades patronais e dos trabalhadores e de outros interesses sócioeconômicos']);
        Profissao::create(['id' => '1143', 'nome' => 'Dirigentes e administradores de entidades religiosas']);
        Profissao::create(['id' => '1144', 'nome' => 'Dirigentes e administradores de organizações da sociedade civil sem fins lucrativos']);
        Profissao::create(['id' => '1210', 'nome' => 'Diretores gerais']);
        Profissao::create(['id' => '1221', 'nome' => 'Diretores de produção e operações em empresa agropecuária, pesqueira , aqüícola e florestal']);
        Profissao::create(['id' => '1222', 'nome' => 'Diretores de produção e operações em empresa da indústria extrativa, transformação e de serviços de utilidade pública']);
        Profissao::create(['id' => '1223', 'nome' => 'Diretores de operações de obras em empresa de construção']);
        Profissao::create(['id' => '1224', 'nome' => 'Diretores de operações em empresa do comércio']);
        Profissao::create(['id' => '1225', 'nome' => 'Diretores de serviços de turismo, de alojamento e de alimentação']);
        Profissao::create(['id' => '1226', 'nome' => 'Diretores de operações de serviços em empresa de armazenamento, de transporte e de telecomunicação']);
        Profissao::create(['id' => '1227', 'nome' => 'Diretores de operações de serviços em instituição de intermediação financeira']);
        Profissao::create(['id' => '1231', 'nome' => 'Diretores administrativos e financeiros']);
        Profissao::create(['id' => '1232', 'nome' => 'Diretores de recursos humanos e relações de trabalho']);
        Profissao::create(['id' => '1233', 'nome' => 'Diretores de comercialização e marketing']);
        Profissao::create(['id' => '1234', 'nome' => 'Diretores de suprimentos e afins']);
        Profissao::create(['id' => '1236', 'nome' => 'Diretores de serviços de informática']);
        Profissao::create(['id' => '1237', 'nome' => 'Diretores de pesquisa e desenvolvimento']);
        Profissao::create(['id' => '1238', 'nome' => 'Diretores de manutenção']);
        Profissao::create(['id' => '1311', 'nome' => 'Diretores e gerentes de operações em empresa de serviços pessoais, sociais e culturais']);
        Profissao::create(['id' => '1312', 'nome' => 'Gestores e especialistas de operações em empresas, secretarias e unidades de serviços de saúde']);
        Profissao::create(['id' => '1313', 'nome' => 'Diretores e gerentes de instituição de serviços educacionais']);
        Profissao::create(['id' => '1411', 'nome' => 'Gerentes de produção e operações em empresa agropecuária, pesqueira, aqüícola e florestal']);
        Profissao::create(['id' => '1412', 'nome' => 'Gerentes de produção e operações em empresa da indústria extrativa, de transformação e de serviços de utilidade pública']);
        Profissao::create(['id' => '1413', 'nome' => 'Gerentes de obras em empresa de construção']);
        Profissao::create(['id' => '1414', 'nome' => 'Gerentes de operações comerciais e de assistência técnica']);
        Profissao::create(['id' => '1415', 'nome' => 'Gerentes de operações de serviços em empresa de turismo, de alojamento e alimentação']);
        Profissao::create(['id' => '1416', 'nome' => 'Gerentes de operações de serviços em empresa de transporte, de comunicação e de logística (armazenagem e distribuição)']);
        Profissao::create(['id' => '1417', 'nome' => 'Gerentes de operações de serviços em instituição de intermediação financeira']);
        Profissao::create(['id' => '1421', 'nome' => 'Gerentes administrativos, financeiros, de riscos e afins']);
        Profissao::create(['id' => '1422', 'nome' => 'Gerentes de recursos humanos e de relações do trabalho']);
        Profissao::create(['id' => '1423', 'nome' => 'Gerentes de comercialização, marketing e comunicação']);
        Profissao::create(['id' => '1424', 'nome' => 'Gerentes de suprimentos e afins']);
        Profissao::create(['id' => '1425', 'nome' => 'Gerentes de tecnologia da informação']);
        Profissao::create(['id' => '1426', 'nome' => 'Gerentes de pesquisa e desenvolvimento e afins']);
        Profissao::create(['id' => '1427', 'nome' => 'Gerentes de manutenção e afins']);
        Profissao::create(['id' => '2011', 'nome' => 'Profissionais da biotecnologia']);
        Profissao::create(['id' => '2012', 'nome' => 'Profissionais da metrologia']);
        Profissao::create(['id' => '2021', 'nome' => 'Engenheiros de controle e automação, engenheiros mecatrônicos e afins']);
        Profissao::create(['id' => '2030', 'nome' => 'Pesquisadores das ciências biológicas']);
        Profissao::create(['id' => '2031', 'nome' => 'Pesquisadores das ciências naturais e exatas']);
        Profissao::create(['id' => '2032', 'nome' => 'Pesquisadores de engenharia e tecnologia']);
        Profissao::create(['id' => '2033', 'nome' => 'Pesquisadores das ciências da saúde']);
        Profissao::create(['id' => '2034', 'nome' => 'Pesquisadores das ciências da agricultura']);
        Profissao::create(['id' => '2035', 'nome' => 'Pesquisadores das ciências sociais e humanas']);
        Profissao::create(['id' => '2041', 'nome' => 'Peritos criminais']);
        Profissao::create(['id' => '2111', 'nome' => 'Profissionais da matemática']);
        Profissao::create(['id' => '2112', 'nome' => 'Profissionais de estatística']);
        Profissao::create(['id' => '2122', 'nome' => 'Engenheiros em computação']);
        Profissao::create(['id' => '2123', 'nome' => 'Administradores de tecnologia da informação']);
        Profissao::create(['id' => '2124', 'nome' => 'Analistas de tecnologia da informação']);
        Profissao::create(['id' => '2131', 'nome' => 'Físicos']);
        Profissao::create(['id' => '2132', 'nome' => 'Químicos']);
        Profissao::create(['id' => '2133', 'nome' => 'Profissionais das ciências atmosféricas e espaciais e de astronomia']);
        Profissao::create(['id' => '2134', 'nome' => 'Geólogos, oceanógrafos, geofísicos e afins']);
        Profissao::create(['id' => '2140', 'nome' => 'Engenheiros ambientais e afins']);
        Profissao::create(['id' => '2141', 'nome' => 'Arquitetos e urbanistas']);
        Profissao::create(['id' => '2142', 'nome' => 'Engenheiros civis e afins']);
        Profissao::create(['id' => '2143', 'nome' => 'Engenheiros eletricistas, eletrônicos e afins']);
        Profissao::create(['id' => '2144', 'nome' => 'Engenheiros mecânicos e afins']);
        Profissao::create(['id' => '2145', 'nome' => 'Engenheiros químicos e afins']);
        Profissao::create(['id' => '2146', 'nome' => 'Engenheiros metalurgistas, de materiais e afins']);
        Profissao::create(['id' => '2147', 'nome' => 'Engenheiros de minas e afins']);
        Profissao::create(['id' => '2148', 'nome' => 'Engenheiros agrimensores e engenheiros cartógrafos']);
        Profissao::create(['id' => '2149', 'nome' => 'Engenheiros de produção, qualidade, segurança e afins']);
        Profissao::create(['id' => '2151', 'nome' => 'Oficiais de convés e afins']);
        Profissao::create(['id' => '2152', 'nome' => 'Oficiais de máquinas da marinha mercante']);
        Profissao::create(['id' => '2153', 'nome' => 'Profissionais da pilotagem aeronáutica']);
        Profissao::create(['id' => '2211', 'nome' => 'Biólogos e afins']);
        Profissao::create(['id' => '2212', 'nome' => 'Biomédicos']);
        Profissao::create(['id' => '2221', 'nome' => 'Engenheiros agrossilvipecuários']);
        Profissao::create(['id' => '2222', 'nome' => 'Engenheiros de alimentos e afins']);
        Profissao::create(['id' => '2232', 'nome' => 'Cirurgiões-dentistas']);
        Profissao::create(['id' => '2233', 'nome' => 'Veterinários e zootecnistas']);
        Profissao::create(['id' => '2234', 'nome' => 'Farmacêuticos']);
        Profissao::create(['id' => '2235', 'nome' => 'Enfermeiros e afins']);
        Profissao::create(['id' => '2236', 'nome' => 'Fisioterapeutas']);
        Profissao::create(['id' => '2237', 'nome' => 'Nutricionistas']);
        Profissao::create(['id' => '2238', 'nome' => 'Fonoaudiólogos']);
        Profissao::create(['id' => '2239', 'nome' => 'Terapeutas ocupacionais, ortoptistas e psicomotricistas']);
        Profissao::create(['id' => '2241', 'nome' => 'Profissionais da educação física']);
        Profissao::create(['id' => '2251', 'nome' => 'Médicos clínicos']);
        Profissao::create(['id' => '2252', 'nome' => 'Médicos em especialidades cirúrgicas']);
        Profissao::create(['id' => '2253', 'nome' => 'Médicos em medicina diagnóstica e terapêutica']);
        Profissao::create(['id' => '2261', 'nome' => 'Osteopatas e quiropraxistas']);
        Profissao::create(['id' => '2263', 'nome' => 'Profissionais das terapias criativas,equoterápicas e naturológicas']);
        Profissao::create(['id' => '2311', 'nome' => 'Professores de nível superior na educação infantil']);
        Profissao::create(['id' => '2312', 'nome' => 'Professores de nível superior do ensino fundamental (primeira a quarta séries)']);
        Profissao::create(['id' => '2313', 'nome' => 'Professores de nível superior no ensino fundamental de quinta a oitava série']);
        Profissao::create(['id' => '2321', 'nome' => 'Professores do ensino médio']);
        Profissao::create(['id' => '2331', 'nome' => 'Professores do ensino profissional']);
        Profissao::create(['id' => '2332', 'nome' => 'Instrutores de ensino profissional']);
        Profissao::create(['id' => '2341', 'nome' => 'Professores de matemática, estatística e informática do ensino superior']);
        Profissao::create(['id' => '2342', 'nome' => 'Professores de ciências físicas, químicas e afins do ensino superior']);
        Profissao::create(['id' => '2343', 'nome' => 'Professores de arquitetura e urbanismo, engenharia, geofísica e geologia do ensino superior']);
        Profissao::create(['id' => '2344', 'nome' => 'Professores de ciências biológicas e da saúde do ensino superior']);
        Profissao::create(['id' => '2345', 'nome' => 'Professores na área de formação pedagógica do ensino superior']);
        Profissao::create(['id' => '2346', 'nome' => 'Professores nas áreas de língua e literatura do ensino superior']);
        Profissao::create(['id' => '2347', 'nome' => 'Professores de ciências humanas do ensino superior']);
        Profissao::create(['id' => '2348', 'nome' => 'Professores de ciências econômicas, administrativas e contábeis do ensino superior']);
        Profissao::create(['id' => '2349', 'nome' => 'Professores de artes do ensino superior']);
        Profissao::create(['id' => '2392', 'nome' => 'Professores de educação especial']);
        Profissao::create(['id' => '2394', 'nome' => 'Programadores, avaliadores e orientadores de ensino']);
        Profissao::create(['id' => '2410', 'nome' => 'Advogados']);
        Profissao::create(['id' => '2412', 'nome' => 'Procuradores e advogados públicos']);
        Profissao::create(['id' => '2413', 'nome' => 'Tabeliães e registradores']);
        Profissao::create(['id' => '2422', 'nome' => 'Membros do ministério público']);
        Profissao::create(['id' => '2423', 'nome' => 'Delegados de polícia']);
        Profissao::create(['id' => '2424', 'nome' => 'Defensores públicos e procuradores da assistência judiciária']);
        Profissao::create(['id' => '2429', 'nome' => 'Profissionais da inteligência']);
        Profissao::create(['id' => '2511', 'nome' => 'Profissionais em pesquisa e análise antropológica sociológica']);
        Profissao::create(['id' => '2512', 'nome' => 'Economistas']);
        Profissao::create(['id' => '2513', 'nome' => 'Profissionais em pesquisa e análise geográfica']);
        Profissao::create(['id' => '2514', 'nome' => 'Filósofos']);
        Profissao::create(['id' => '2515', 'nome' => 'Psicólogos e psicanalistas']);
        Profissao::create(['id' => '2516', 'nome' => 'Assistentes sociais e economistas domésticos']);
        Profissao::create(['id' => '2521', 'nome' => 'Administradores']);
        Profissao::create(['id' => '2522', 'nome' => 'Contadores e afins']);
        Profissao::create(['id' => '2523', 'nome' => 'Secretárias(os) executivas(os) e afins']);
        Profissao::create(['id' => '2524', 'nome' => 'Profissionais de recursos humanos']);
        Profissao::create(['id' => '2525', 'nome' => 'Profissionais de administração ecônomico-financeira']);
        Profissao::create(['id' => '2526', 'nome' => 'Profissionais da administração dos serviços de segurança']);
        Profissao::create(['id' => '2527', 'nome' => 'Profissionais de planejamento, programação e controles logisticos']);
        Profissao::create(['id' => '2531', 'nome' => 'Profissionais de publicidade']);
        Profissao::create(['id' => '2532', 'nome' => 'Profissionais de comercializacão e consultoria de serviços bancários']);
        Profissao::create(['id' => '2533', 'nome' => 'Corretores de valores, ativos financeiros, mercadorias e derivativos']);
        Profissao::create(['id' => '2541', 'nome' => 'Auditores fiscais e técnicos da receita federal']);
        Profissao::create(['id' => '2542', 'nome' => 'Auditores fiscais da previdência social']);
        Profissao::create(['id' => '2543', 'nome' => 'Auditores fiscais do trabalho']);
        Profissao::create(['id' => '2544', 'nome' => 'Fiscais de tributos estaduais e municipais']);
        Profissao::create(['id' => '2545', 'nome' => 'Profissionais da fiscalização de atividades urbanas']);
        Profissao::create(['id' => '2611', 'nome' => 'Profissionais do jornalismo']);
        Profissao::create(['id' => '2612', 'nome' => 'Profissionais da informação']);
        Profissao::create(['id' => '2613', 'nome' => 'Arquivistas e museólogos']);
        Profissao::create(['id' => '2614', 'nome' => 'Filólogos,tradutores ,intérpretes e afins']);
        Profissao::create(['id' => '2615', 'nome' => 'Profissionais da escrita']);
        Profissao::create(['id' => '2616', 'nome' => 'Editores']);
        Profissao::create(['id' => '2617', 'nome' => 'Locutores, comentaristas e repórteres de mídias audiovisuais']);
        Profissao::create(['id' => '2618', 'nome' => 'Fotógrafos profissionais']);
        Profissao::create(['id' => '2619', 'nome' => 'Assistentes de direção (tv) e continuístas']);
        Profissao::create(['id' => '2621', 'nome' => 'Produtores artísticos e culturais']);
        Profissao::create(['id' => '2622', 'nome' => 'Diretores de espetáculos e afins']);
        Profissao::create(['id' => '2623', 'nome' => 'Cenógrafos']);
        Profissao::create(['id' => '2624', 'nome' =>'Artistas visuais,desenhistas industriais e conservadores-restauradores de bens culturais']);
        Profissao::create(['id' => '2625', 'nome' =>'Atores']);
        Profissao::create(['id' => '2626', 'nome' =>'Músicos compositores, arranjadores, regentes e musicólogos']);
        Profissao::create(['id' => '2627', 'nome' =>'Músicos intérpretes']);
        Profissao::create(['id' => '2628', 'nome' =>'Artistas da dança (exceto dança tradicional e popular)']);
        Profissao::create(['id' => '2629', 'nome' =>'Designer de interiores de nível superior']);
        Profissao::create(['id' => '2631', 'nome' =>'Ministros de culto, missionários, teólogos e profissionais assemelhados']);
        Profissao::create(['id' => '2711', 'nome' =>'Chefes de cozinha e afins']);
        Profissao::create(['id' => '3001', 'nome' =>'Técnicos em mecatrônica']);
        Profissao::create(['id' => '3003', 'nome' =>'Técnicos em eletromecânica']);
        Profissao::create(['id' => '3011', 'nome' =>'Técnicos de laboratório industrial']);
        Profissao::create(['id' => '3012', 'nome' =>'Técnicos de apoio à bioengenharia']);
        Profissao::create(['id' => '3111', 'nome' =>'Técnicos químicos']);
        Profissao::create(['id' => '3112', 'nome' =>'Técnicos de produção de indústrias químicas, petroquímicas, refino de petróleo, gás e afins']);
        Profissao::create(['id' => '3113', 'nome' =>'Técnicos em materiais, produtos cerâmicos e vidros']);
        Profissao::create(['id' => '3114', 'nome' =>'Técnicos em fabricação de produtos plásticos e de borracha']);
        Profissao::create(['id' => '3115', 'nome' =>'Técnicos em controle ambiental, utilidades e tratamento de efluentes']);
        Profissao::create(['id' => '3116', 'nome' =>'Técnicos têxteis']);
        Profissao::create(['id' => '3117', 'nome' =>'Coloristas']);
        Profissao::create(['id' => '3121', 'nome' =>'Técnicos em construção civil (edificações)']);
        Profissao::create(['id' => '3122', 'nome' =>'Técnicos em construção civil (obras de infraestrutura)']);
        Profissao::create(['id' => '3123', 'nome' =>'Técnicos em geomática']);
        Profissao::create(['id' => '3131', 'nome' =>'Técnicos em eletricidade e eletrotécnica']);
        Profissao::create(['id' => '3132', 'nome' =>'Técnicos em eletrônica']);
        Profissao::create(['id' => '3133', 'nome' =>'Técnicos em telecomunicações']);
        Profissao::create(['id' => '3134', 'nome' =>'Técnicos em calibração e instrumentação']);
        Profissao::create(['id' => '3135', 'nome' =>'Técnicos em fotônica']);
        Profissao::create(['id' => '3141', 'nome' =>'Técnicos mecânicos na fabricação e montagem de máquinas, sistemas e instrumentos']);
        Profissao::create(['id' => '3142', 'nome' =>'Técnicos mecânicos (ferramentas)']);
        Profissao::create(['id' => '3143', 'nome' =>'Técnicos em mecânica veicular']);
        Profissao::create(['id' => '3144', 'nome' =>'Técnicos mecânicos na manutenção de máquinas, sistemas e instrumentos']);
        Profissao::create(['id' => '3146', 'nome' =>'Técnicos em metalurgia (estruturas metálicas)']);
        Profissao::create(['id' => '3147', 'nome' =>'Técnicos em siderurgia']);
        Profissao::create(['id' => '3161', 'nome' =>'Técnicos em geologia']);
        Profissao::create(['id' => '3163', 'nome' =>'Técnicos em mineração']);
        Profissao::create(['id' => '3171', 'nome' =>'Técnicos de desenvolvimento de sistemas e aplicações']);
        Profissao::create(['id' => '3172', 'nome' =>'Técnicos em operação e monitoração de computadores']);
        Profissao::create(['id' => '3180', 'nome' =>'Desenhistas técnicos, em geral']);
        Profissao::create(['id' => '3181', 'nome' =>'Desenhistas técnicos da construção civil e arquitetura']);
        Profissao::create(['id' => '3182', 'nome' =>'Desenhistas técnicos da mecânica']);
        Profissao::create(['id' => '3183', 'nome' =>'Desenhistas técnicos em eletricidade, eletrônica, eletromecânica, calefação, ventilação e refrigeração']);
        Profissao::create(['id' => '3184', 'nome' =>'Desenhistas técnicos de produtos e serviços diversos']);
        Profissao::create(['id' => '3185', 'nome' =>'Desenhistas projetistas de construção civil e arquitetura']);
        Profissao::create(['id' => '3186', 'nome' =>'Desenhistas projetistas da mecânica']);
        Profissao::create(['id' => '3187', 'nome' =>'Desenhistas projetistas da eletrônica']);
        Profissao::create(['id' => '3188', 'nome' =>'Desenhistas projetistas e modelistas de produtos e serviços diversos']);
        Profissao::create(['id' => '3191', 'nome' =>'Técnicos do vestuário']);
        Profissao::create(['id' => '3192', 'nome' =>'Técnicos do mobiliário e afins']);
        Profissao::create(['id' => '3201', 'nome' =>'Técnicos em biologia']);
        Profissao::create(['id' => '3211', 'nome' =>'Técnicos agrícolas']);
        Profissao::create(['id' => '3212', 'nome' =>'Técnicos florestais']);
        Profissao::create(['id' => '3213', 'nome' =>'Técnicos em aqüicultura']);
        Profissao::create(['id' => '3221', 'nome' =>'Tecnólogos e técnicos em terapias complementares e estéticas']);
        Profissao::create(['id' => '3222', 'nome' =>'Técnicos e auxiliares de enfermagem']);
        Profissao::create(['id' => '3223', 'nome' =>'Técnicos em óptica e optometria']);
        Profissao::create(['id' => '3224', 'nome' =>'Técnicos de odontologia']);
        Profissao::create(['id' => '3225', 'nome' =>'Técnicos em próteses ortopédicas']);
        Profissao::create(['id' => '3226', 'nome' =>'Técnicos de imobilizações ortopédicas']);
        Profissao::create(['id' => '3231', 'nome' =>'Técnicos em pecuária']);
        Profissao::create(['id' => '3241', 'nome' =>'Tecnólogos e técnicos em métodos de diagnósticos e terapêutica']);
        Profissao::create(['id' => '3242', 'nome' =>'Técnicos de laboratórios de saúde e bancos de sangue']);
        Profissao::create(['id' => '3250', 'nome' =>'Enólogos, perfumistas e aromistas']);
        Profissao::create(['id' => '3251', 'nome' =>'Técnico em farmácia e em manipulação farmacêutica']);
        Profissao::create(['id' => '3252', 'nome' =>'Técnicos em produção, conservação  e de qualidade de alimentos']);
        Profissao::create(['id' => '3253', 'nome' =>'Técnicos de apoio à biotecnologia']);
        Profissao::create(['id' => '3281', 'nome' =>'Técnicos em necrópsia e taxidermistas']);
        Profissao::create(['id' => '3311', 'nome' =>'Professores de nível médio na educação infantil']);
        Profissao::create(['id' => '3312', 'nome' =>'Professores de nível médio no ensino fundamental']);
        Profissao::create(['id' => '3313', 'nome' =>'Professores de nível médio no ensino profissionalizante']);
        Profissao::create(['id' => '3321', 'nome' =>'Professores leigos no ensino fundamental']);
        Profissao::create(['id' => '3322', 'nome' =>'Professores práticos no ensino profissionalizante']);
        Profissao::create(['id' => '3331', 'nome' =>'Instrutores e professores de cursos livres']);
        Profissao::create(['id' => '3341', 'nome' =>'Inspetores de alunos e afins']);
        Profissao::create(['id' => '3411', 'nome' =>'Pilotos de aviação comercial, mecânicos de vôo e afins']);
        Profissao::create(['id' => '3412', 'nome' =>'Técnicos marítimos, fluviários e pescadores de convés']);
        Profissao::create(['id' => '3413', 'nome' =>'Técnicos marítimos e fluviários de máquinas']);
        Profissao::create(['id' => '3421', 'nome' =>'Especialistas em logística de transportes']);
        Profissao::create(['id' => '3422', 'nome' =>'Despachantes aduaneiros']);
        Profissao::create(['id' => '3423', 'nome' =>'Técnicos em transportes rodoviários']);
        Profissao::create(['id' => '3424', 'nome' =>'Técnicos em transportes metroferroviários']);
        Profissao::create(['id' => '3425', 'nome' =>'Técnicos em transportes aéreos']);
        Profissao::create(['id' => '3426', 'nome' =>'Técnicos em transportes por vias navegáveis e operações portuárias']);
        Profissao::create(['id' => '3511', 'nome' =>'Técnicos em contabilidade']);
        Profissao::create(['id' => '3513', 'nome' =>'Técnicos em administração']);
        Profissao::create(['id' => '3514', 'nome' =>'Serventuários da justiça e afins']);
        Profissao::create(['id' => '3515', 'nome' =>'Técnicos em secretariado, taquígrafos e estenotipistas']);
        Profissao::create(['id' => '3516', 'nome' =>'Técnicos em segurança do trabalho']);
        Profissao::create(['id' => '3517', 'nome' =>'Técnicos de seguros e afins']);
        Profissao::create(['id' => '3518', 'nome' =>'Agentes de investigação e identificação']);
        Profissao::create(['id' => '3519', 'nome' =>'Técnicos da inteligência']);
        Profissao::create(['id' => '3522', 'nome' =>'Agentes da saúde e do meio ambiente']);
        Profissao::create(['id' => '3523', 'nome' =>'Agentes  fiscais metrológicos e de qualidade']);
        Profissao::create(['id' => '3524', 'nome' =>'Profissionais de direitos autorais e de avaliacão de produtos dos meios de comunicação']);
        Profissao::create(['id' => '3532', 'nome' =>'Técnicos em operações e serviços bancários']);
        Profissao::create(['id' => '3541', 'nome' =>'Especialistas em promoção de produtos e vendas']);
        Profissao::create(['id' => '3542', 'nome' =>'Compradores']);
        Profissao::create(['id' => '3543', 'nome' =>'Analistas de comércio exterior']);
        Profissao::create(['id' => '3544', 'nome' =>'Leiloeiros e avaliadores']);
        Profissao::create(['id' => '3545', 'nome' =>'Corretores de seguros']);
        Profissao::create(['id' => '3546', 'nome' =>'Corretores de imóveis']);
        Profissao::create(['id' => '3547', 'nome' =>'Representantes comerciais autônomos']);
        Profissao::create(['id' => '3548', 'nome' =>'Técnicos em serviços de turismo e organização de eventos']);
        Profissao::create(['id' => '3711', 'nome' =>'Técnicos em biblioteconomia']);
        Profissao::create(['id' => '3712', 'nome' =>'Técnicos em museologia e afins']);
        Profissao::create(['id' => '3713', 'nome' =>'Técnicos em artes gráficas']);
        Profissao::create(['id' => '3714', 'nome' =>'Recreadores']);
        Profissao::create(['id' => '3721', 'nome' =>'Captadores de imagens em movimento']);
        Profissao::create(['id' => '3722', 'nome' =>'Operadores de rede de teleprocessamento e afins']);
        Profissao::create(['id' => '3731', 'nome' =>'Técnicos de operação de registros sonoro/audiovisuais']);
        Profissao::create(['id' => '3732', 'nome' =>'Supervisores operacionais e técnicos em mídias audiovisuais']);
        Profissao::create(['id' => '3741', 'nome' =>'Técnicos em áudio']);
        Profissao::create(['id' => '3742', 'nome' =>'Técnicos em cenografia']);
        Profissao::create(['id' => '3743', 'nome' =>'Técnicos em operação de aparelhos de projeção']);
        Profissao::create(['id' => '3744', 'nome' =>'Técnicos em montagem, edição e finalização de mídia audiovisual']);
        Profissao::create(['id' => '3751', 'nome' =>'Designers de interiores, de vitrines e visual merchandiser e afins (nível médio)']);
        Profissao::create(['id' => '3761', 'nome' =>'Dançarinos tradicionais e populares']);
        Profissao::create(['id' => '3762', 'nome' =>'Artistas de circo (circenses)']);
        Profissao::create(['id' => '3763', 'nome' =>'Apresentadores de eventos, programas e espetáculos']);
        Profissao::create(['id' => '3764', 'nome' =>'Modelos']);
        Profissao::create(['id' => '3771', 'nome' =>'Atletas profissionais']);
        Profissao::create(['id' => '3772', 'nome' =>'Árbitros desportivos']);
        Profissao::create(['id' => '3911', 'nome' =>'Técnicos de planejamento e controle de produção']);
        Profissao::create(['id' => '3912', 'nome' =>'Técnicos de controle da produção']);
        Profissao::create(['id' => '3951', 'nome' =>'Técnicos de apoio em pesquisa e desenvolvimento']);
        Profissao::create(['id' => '4101', 'nome' =>'Supervisores administrativos']);
        Profissao::create(['id' => '4102', 'nome' =>'Supervisores de serviços financeiros, de câmbio e de controle']);
        Profissao::create(['id' => '4110', 'nome' =>'Agentes, assistentes e auxiliares administrativos']);
        Profissao::create(['id' => '4121', 'nome' =>'Operadores de equipamentos de entrada e transmissão de dados']);
        Profissao::create(['id' => '4122', 'nome' => 'Contínuos']);
        Profissao::create(['id' => '4131', 'nome' => 'Auxiliares de contabilidade']);
        Profissao::create(['id' => '4132', 'nome' => 'Escriturários de serviços bancários']);
        Profissao::create(['id' => '4141', 'nome' => 'Almoxarifes e armazenistas']);
        Profissao::create(['id' => '4142', 'nome' => 'Apontadores e conferentes']);
        Profissao::create(['id' => '4151', 'nome' => 'Auxiliares de serviços de documentação, informação e pesquisa']);
        Profissao::create(['id' => '4152', 'nome' => 'Trabalhadores nos serviços de classificação e entregas de correspondências, encomendas e publicações']);
        Profissao::create(['id' => '4153', 'nome' => 'Trabalhadores em registros e informações em saúde']);
        Profissao::create(['id' => '4201', 'nome' => 'Supervisores de atendimento ao público e de pesquisa']);
        Profissao::create(['id' => '4211', 'nome' => 'Caixas e bilheteiros (exceto caixa de banco)']);
        Profissao::create(['id' => '4212', 'nome' => 'Coletadores de apostas e de jogos']);
        Profissao::create(['id' => '4213', 'nome' => 'Cobradores e afins']);
        Profissao::create(['id' => '4221', 'nome' => 'Recepcionistas']);
        Profissao::create(['id' => '4222', 'nome' => 'Operadores de telefonia']);
        Profissao::create(['id' => '4223', 'nome' => 'Operadores de telemarketing']);
        Profissao::create(['id' => '4231', 'nome' => 'Despachantes documentalistas e afins']);
        Profissao::create(['id' => '4241', 'nome' => 'Entrevistadores e recenseadores']);
        Profissao::create(['id' => '4242', 'nome' => 'Aplicadores de provas e afins']);
        Profissao::create(['id' => '5101', 'nome' => 'Supervisores dos serviços de transporte, turismo, hotelaria e administração de edifícios']);
        Profissao::create(['id' => '5102', 'nome' => 'Supervisores de lavanderia']);
        Profissao::create(['id' => '5103', 'nome' => 'Supervisores dos serviços de proteção, segurança e outros']);
        Profissao::create(['id' => '5111', 'nome' => 'Trabalhadores de segurança e atendimento aos usuários nos transportes']);
        Profissao::create(['id' => '5112', 'nome' => 'Fiscais e cobradores dos transportes coletivos']);
        Profissao::create(['id' => '5114', 'nome' => 'Guias de turismo']);
        Profissao::create(['id' => '5115', 'nome' => 'Condutores de turismo']);
        Profissao::create(['id' => '5121', 'nome' => 'Trabalhadores dos serviços domésticos em geral']);
        Profissao::create(['id' => '5131', 'nome' => 'Mordomos e governantas']);
        Profissao::create(['id' => '5132', 'nome' => 'Cozinheiros']);
        Profissao::create(['id' => '5133', 'nome' => 'Camareiros, roupeiros e afins']);
        Profissao::create(['id' => '5134', 'nome' => 'Trabalhadores no atendimento em estabelecimentos de serviços de alimentação, bebidas e hotelaria']);
        Profissao::create(['id' => '5135', 'nome' => 'Trabalhadores auxiliares nos serviços de alimentação']);
        Profissao::create(['id' => '5136', 'nome' => 'Churrasqueiros, pizzaiolos e sushimen']);
        Profissao::create(['id' => '5141', 'nome' => 'Trabalhadores nos serviços de administração de edifícios']);
        Profissao::create(['id' => '5142', 'nome' => 'Trabalhadores nos serviços de coleta de resíduos, de limpeza e conservação de áreas públicas']);
        Profissao::create(['id' => '5143', 'nome' => 'Trabalhadores nos  serviços de manutenção de edificações']);
        Profissao::create(['id' => '5151', 'nome' => 'Trabalhadores em serviços de promoção e apoio à saúde']);
        Profissao::create(['id' => '5152', 'nome' => 'Auxiliares de laboratório da saúde']);
        Profissao::create(['id' => '5153', 'nome' => 'Trabalhadores de atenção, defesa e proteção a pessoas em situação de risco e adolescentes em conflito com a lei']);
        Profissao::create(['id' => '5161', 'nome' => 'Trabalhadores nos serviços de embelezamento e higiene']);
        Profissao::create(['id' => '5162', 'nome' => 'Cuidadores de crianças, jovens, adultos e idosos']);
        Profissao::create(['id' => '5163', 'nome' => 'Tintureiros, lavadeiros e afins, a máquina']);
        Profissao::create(['id' => '5164', 'nome' => 'Lavadores e passadores de roupa, a mão']);
        Profissao::create(['id' => '5165', 'nome' => 'Trabalhadores dos serviços funerários']);
        Profissao::create(['id' => '5166', 'nome' => 'Trabalhadores auxiliares dos serviços funerários']);
        Profissao::create(['id' => '5167', 'nome' => 'Astrólogos e numerólogos']);
        Profissao::create(['id' => '5168', 'nome' => 'Esotéricos e paranormais']);
        Profissao::create(['id' => '5171', 'nome' => 'Bombeiros e salva-vidas']);
        Profissao::create(['id' => '5172', 'nome' => 'Policiais, guardas-civis municipais e agentes de trânsito']);
        Profissao::create(['id' => '5173', 'nome' => 'Vigilantes e guardas de segurança']);
        Profissao::create(['id' => '5174', 'nome' => 'Porteiros, vigias e afins']);
        Profissao::create(['id' => '5191', 'nome' => 'Motociclistas e ciclistas de entregas rápidas']);
        Profissao::create(['id' => '5192', 'nome' => 'Trabalhadores da coleta e seleção de material reciclável']);
        Profissao::create(['id' => '5193', 'nome' => 'Trabalhadores de serviços veterinários, de higiene e estética de animais domésticos']);
        Profissao::create(['id' => '5198', 'nome' => 'Profissionais do sexo']);
        Profissao::create(['id' => '5199', 'nome' => 'Outros trabalhadores dos serviços']);
        Profissao::create(['id' => '5201', 'nome' => 'Supervisores de vendas e de prestação de serviços']);
        Profissao::create(['id' => '5211', 'nome' => 'Operadores do comércio em lojas e mercados']);
        Profissao::create(['id' => '5231', 'nome' => 'Instaladores de produtos e acessórios']);
        Profissao::create(['id' => '5241', 'nome' => 'Vendedores em domicílio']);
        Profissao::create(['id' => '5242', 'nome' => 'Vendedores em bancas, quiosques e barracas']);
        Profissao::create(['id' => '5243', 'nome' => 'Vendedores ambulantes']);
        Profissao::create(['id' => '6110', 'nome' => 'Produtores agropecuários em geral']);
        Profissao::create(['id' => '6120', 'nome' => 'Produtores agrícolas polivalentes']);
        Profissao::create(['id' => '6121', 'nome' => 'Produtores agrícolas na cultura de gramíneas']);
        Profissao::create(['id' => '6122', 'nome' => 'Produtores agrícolas na cultura de plantas fibrosas']);
        Profissao::create(['id' => '6123', 'nome' => 'Produtores agrícolas na olericultura']);
        Profissao::create(['id' => '6124', 'nome' => 'Produtores agrícolas no cultivo de flores e plantas ornamentais']);
        Profissao::create(['id' => '6125', 'nome' => 'Produtores agrícolas na fruticultura']);
        Profissao::create(['id' => '6126', 'nome' => 'Produtores agrícolas na cultura de plantas estimulantes']);
        Profissao::create(['id' => '6127', 'nome' => 'Produtores agrícolas na cultura de plantas oleaginosas']);
        Profissao::create(['id' => '6128', 'nome' => 'Produtores de especiarias e de plantas aromáticas e medicinais']);
        Profissao::create(['id' => '6130', 'nome' => 'Produtores em pecuária polivalente']);
        Profissao::create(['id' => '6131', 'nome' => 'Produtores em pecuária de animais de grande porte']);
        Profissao::create(['id' => '6132', 'nome' => 'Produtores em pecuária de animais de médio porte']);
        Profissao::create(['id' => '6133', 'nome' => 'Produtores da avicultura e cunicultura']);
        Profissao::create(['id' => '6134', 'nome' => 'Produtores de animais e insetos úteis']);
        Profissao::create(['id' => '6201', 'nome' => 'Supervisores na exploração agropecuária']);
        Profissao::create(['id' => '6210', 'nome' => 'Trabalhadores agropecuários em geral']);
        Profissao::create(['id' => '6220', 'nome' => 'Trabalhadores de apoio à agricultura']);
        Profissao::create(['id' => '6221', 'nome' => 'Trabalhadores agrícolas na cultura de gramíneas']);
        Profissao::create(['id' => '6222', 'nome' => 'Trabalhadores agrícolas na cultura de plantas fibrosas']);
        Profissao::create(['id' => '6223', 'nome' => 'Trabalhadores agrícolas na olericultura']);
        Profissao::create(['id' => '6224', 'nome' => 'Trabalhadores agrícolas no cultivo de flores e plantas ornamentais']);
        Profissao::create(['id' => '6225', 'nome' => 'Trabalhadores agrícolas na fruticultura']);
        Profissao::create(['id' => '6226', 'nome' => 'Trabalhadores agrícolas nas culturas de plantas estimulantes']);
        Profissao::create(['id' => '6227', 'nome' => 'Trabalhadores agrícolas na cultura de plantas oleaginosas']);
        Profissao::create(['id' => '6228', 'nome' => 'Trabalhadores agrícolas da cultura de especiarias e de plantas aromáticas e medicinais']);
        Profissao::create(['id' => '6230', 'nome' => 'Tratadores polivalentes de animais']);
        Profissao::create(['id' => '6231', 'nome' => 'Trabalhadores na pecuária de animais de grande porte']);
        Profissao::create(['id' => '6232', 'nome' => 'Trabalhadores na pecuária de animais de médio porte']);
        Profissao::create(['id' => '6233', 'nome' => 'Trabalhadores na avicultura e cunicultura']);
        Profissao::create(['id' => '6234', 'nome' => 'Trabalhadores na criação de insetos e animais úteis']);
        Profissao::create(['id' => '6301', 'nome' => 'Supervisores na área florestal e aqüicultura']);
        Profissao::create(['id' => '6310', 'nome' => 'Pescadores polivalentes']);
        Profissao::create(['id' => '6311', 'nome' => 'Pescadores profissionais artesanais de água doce']);
        Profissao::create(['id' => '6312', 'nome' => 'Pescadores de água costeira e alto mar']);
        Profissao::create(['id' => '6313', 'nome' => 'Criadores de animais aquáticos']);
        Profissao::create(['id' => '6314', 'nome' => 'Trabalhadores de apoio à pesca']);
        Profissao::create(['id' => '6320', 'nome' => 'Trabalhadores florestais polivalentes']);
        Profissao::create(['id' => '6321', 'nome' => 'Extrativistas e reflorestadores de espécies produtoras de madeira']);
        Profissao::create(['id' => '6322', 'nome' => 'Extrativistas florestais de espécies produtoras de gomas e resinas']);
        Profissao::create(['id' => '6323', 'nome' => 'Extrativistas florestais de espécies produtoras de fibras, ceras e óleos']);
        Profissao::create(['id' => '6324', 'nome' => 'Extrativistas florestais de espécies produtoras de alimentos silvestres']);
        Profissao::create(['id' => '6325', 'nome' => 'Extrativistas florestais de espécies produtoras de substâncias aromáticas, medicinais e tóxicas']);
        Profissao::create(['id' => '6326', 'nome' => 'Carvoejadores']);
        Profissao::create(['id' => '6410', 'nome' => 'Trabalhadores da mecanização agrícola']);
        Profissao::create(['id' => '6420', 'nome' => 'Trabalhadores da mecanização florestal']);
        Profissao::create(['id' => '6430', 'nome' => 'Trabalhadores da irrigação e drenagem']);
        Profissao::create(['id' => '7101', 'nome' => 'Supervisores da extração mineral']);
        Profissao::create(['id' => '7102', 'nome' => 'Supervisores da construção civil']);
        Profissao::create(['id' => '7111', 'nome' => 'Trabalhadores da extração de minerais sólidos']);
        Profissao::create(['id' => '7112', 'nome' => 'Trabalhadores de extração de minerais sólidos (operadores de máquinas)']);
        Profissao::create(['id' => '7113', 'nome' => 'Trabalhadores da extração de minerais líquidos e gasosos']);
        Profissao::create(['id' => '7114', 'nome' => 'Garimpeiros e operadores de salinas']);
        Profissao::create(['id' => '7121', 'nome' => 'Trabalhadores de beneficiamento de minérios']);
        Profissao::create(['id' => '7122', 'nome' => 'Trabalhadores de beneficiamento de pedras ornamentais']);
        Profissao::create(['id' => '7151', 'nome' => 'Trabalhadores na operação de máquinas de terraplenagem e fundações']);
        Profissao::create(['id' => '7152', 'nome' => 'Trabalhadores de estruturas de alvenaria']);
        Profissao::create(['id' => '7153', 'nome' => 'Montadores de estruturas de concreto armado']);
        Profissao::create(['id' => '7154', 'nome' => 'Trabalhadores na operação de máquinas de concreto usinado']);
        Profissao::create(['id' => '7155', 'nome' => 'Trabalhadores de montagem de estruturas de madeira, metal e compósitos em obras civis']);
        Profissao::create(['id' => '7156', 'nome' => 'Trabalhadores de instalações elétricas']);
        Profissao::create(['id' => '7157', 'nome' => 'Aplicadores de materiais isolantes']);
        Profissao::create(['id' => '7161', 'nome' => 'Revestidores de concreto']);
        Profissao::create(['id' => '7162', 'nome' => 'Telhadores (revestimentos rígidos)']);
        Profissao::create(['id' => '7163', 'nome' => 'Vidraceiros (revestimentos rígidos)']);
        Profissao::create(['id' => '7164', 'nome' => 'Gesseiros']);
        Profissao::create(['id' => '7165', 'nome' => 'Aplicadores de revestimentos cerâmicos, pastilhas, pedras e madeiras']);
        Profissao::create(['id' => '7166', 'nome' => 'Pintores de obras e revestidores de interiores (revestimentos flexíveis)']);
        Profissao::create(['id' => '7170', 'nome' => 'Ajudantes de obras civis']);
        Profissao::create(['id' => '7201', 'nome' => 'Supervisores de usinagem, conformação e tratamento de metais']);
        Profissao::create(['id' => '7202', 'nome' => 'Supervisores da fabricação e montagem metalmecânica']);
        Profissao::create(['id' => '7211', 'nome' => 'Ferramenteiros e afins']);
        Profissao::create(['id' => '7212', 'nome' => 'Preparadores e operadores de máquinas-ferramenta convencionais']);
        Profissao::create(['id' => '7213', 'nome' => 'Afiadores e polidores de metais']);
        Profissao::create(['id' => '7214', 'nome' => 'Operadores de máquinas de usinagem cnc']);
        Profissao::create(['id' => '7221', 'nome' => 'Trabalhadores de forjamento de metais']);
        Profissao::create(['id' => '7222', 'nome' => 'Trabalhadores de fundição de metais puros e de ligas metálicas']);
        Profissao::create(['id' => '7223', 'nome' => 'Trabalhadores de moldagem de metais e de ligas metálicas']);
        Profissao::create(['id' => '7224', 'nome' => 'Trabalhadores de trefilação e estiramento de metais puros e ligas metálicas']);
        Profissao::create(['id' => '7231', 'nome' => 'Trabalhadores de tratamento térmico de metais']);
        Profissao::create(['id' => '7232', 'nome' => 'Trabalhadores de tratamento de superfícies de metais e de compósitos (termoquímicos)']);
        Profissao::create(['id' => '7233', 'nome' => 'Trabalhadores da pintura de equipamentos, veículos, estruturas metálicas e de compósitos']);
        Profissao::create(['id' => '7241', 'nome' => 'Encanadores e instaladores de tubulações']);
        Profissao::create(['id' => '7242', 'nome' => 'Trabalhadores de traçagem e montagem de estruturas metálicas e de compósitos']);
        Profissao::create(['id' => '7243', 'nome' => 'Trabalhadores de soldagem e corte de ligas metálicas']);
        Profissao::create(['id' => '7244', 'nome' => 'Trabalhadores de caldeiraria e serralheria']);
        Profissao::create(['id' => '7245', 'nome' => 'Operadores de máquinas de conformação de metais']);
        Profissao::create(['id' => '7246', 'nome' => 'Trançadores e laceiros de cabos de aço']);
        Profissao::create(['id' => '7250', 'nome' => 'Ajustadores mecânicos polivalentes']);
        Profissao::create(['id' => '7251', 'nome' => 'Montadores de máquinas, aparelhos e acessórios em linhas de montagem']);
        Profissao::create(['id' => '7252', 'nome' => 'Montadores de máquinas industriais']);
        Profissao::create(['id' => '7253', 'nome' => 'Montadores de máquinas pesadas e equipamentos agrícolas']);
        Profissao::create(['id' => '7254', 'nome' => 'Mecânicos montadores de motores e turboalimentadores']);
        Profissao::create(['id' => '7255', 'nome' => 'Montadores de veículos automotores (linha de montagem)']);
        Profissao::create(['id' => '7256', 'nome' => 'Montadores de sistemas e estruturas de aeronaves']);
        Profissao::create(['id' => '7257', 'nome' => 'Instaladores de equipamentos de refrigeração e ventilação']);
        Profissao::create(['id' => '7301', 'nome' => 'Supervisores de montagens e instalações eletroeletrônicas']);
        Profissao::create(['id' => '7311', 'nome' => 'Montadores de equipamentos eletroeletrônicos']);
        Profissao::create(['id' => '7312', 'nome' => 'Montadores de aparelhos de telecomunicações']);
        Profissao::create(['id' => '7313', 'nome' => 'Instaladores-reparadores de  linhas e equipamentos de telecomunicações']);
        Profissao::create(['id' => '7321', 'nome' => 'Instaladores e reparadores de linhas e cabos elétricos, telefônicos e de comunicação de dados']);
        Profissao::create(['id' => '7401', 'nome' => 'Supervisores da mecânica de precisão e instrumentos musicais']);
        Profissao::create(['id' => '7411', 'nome' => 'Mecânicos de instrumentos de precisão']);
        Profissao::create(['id' => '7421', 'nome' => 'Confeccionadores de instrumentos musicais']);
        Profissao::create(['id' => '7501', 'nome' => 'Supervisores de joalheria e afins']);
        Profissao::create(['id' => '7502', 'nome' => 'Supervisores de vidraria, cerâmica e afins']);
        Profissao::create(['id' => '7510', 'nome' => 'Joalheiros e lapidadores de gemas']);
        Profissao::create(['id' => '7511', 'nome' => 'Artesãos de metais preciosos e semi-preciosos']);
        Profissao::create(['id' => '7521', 'nome' => 'Sopradores, moldadores e modeladores de vidros e afins']);
        Profissao::create(['id' => '7522', 'nome' => 'Trabalhadores da transformação de vidros planos']);
        Profissao::create(['id' => '7523', 'nome' => 'Ceramistas (preparação e fabricação)']);
        Profissao::create(['id' => '7524', 'nome' => 'Vidreiros e ceramistas (arte e decoração)']);
        Profissao::create(['id' => '7601', 'nome' => 'Supervisores da indústria têxtil']);
        Profissao::create(['id' => '7602', 'nome' => 'Supervisores na indústria do curtimento']);
        Profissao::create(['id' => '7603', 'nome' => 'Supervisores na confecção do vestuário']);
        Profissao::create(['id' => '7604', 'nome' => 'Supervisores na confecção de calçados']);
        Profissao::create(['id' => '7605', 'nome' => 'Supervisores da confecção de artefatos de tecidos, couros e afins']);
        Profissao::create(['id' => '7606', 'nome' => 'Supervisores das artes gráficas']);
        Profissao::create(['id' => '7610', 'nome' => 'Trabalhadores polivalentes das indústrias têxteis']);
        Profissao::create(['id' => '7611', 'nome' => 'Trabalhadores da classificação de fibras têxteis e lavagem de lã']);
        Profissao::create(['id' => '7612', 'nome' => 'Operadores da fiação']);
        Profissao::create(['id' => '7613', 'nome' => 'Operadores de tear e máquinas similares']);
        Profissao::create(['id' => '7614', 'nome' => 'Trabalhadores de acabamento, tingimento e estamparia das indústrias têxteis']);
        Profissao::create(['id' => '7618', 'nome' => 'Inspetores e revisores de produção têxtil']);
        Profissao::create(['id' => '7620', 'nome' => 'Trabalhadores polivalentes do curtimento de couros e peles']);
        Profissao::create(['id' => '7621', 'nome' => 'Trabalhadores da preparação do curtimento de couros e peles']);
        Profissao::create(['id' => '7622', 'nome' => 'Trabalhadores do curtimento de couros e peles']);
        Profissao::create(['id' => '7623', 'nome' => 'Trabalhadores do acabamento de couros e peles']);
        Profissao::create(['id' => '7630', 'nome' => 'Profissionais polivalentes da confecção de roupas']);
        Profissao::create(['id' => '7631', 'nome' => 'Trabalhadores da preparação da confecção de roupas']);
        Profissao::create(['id' => '7632', 'nome' => 'Operadores de máquinas para costura de peças do vestuário']);
        Profissao::create(['id' => '7633', 'nome' => 'Operadores de máquinas para bordado e acabamento de roupas']);
        Profissao::create(['id' => '7640', 'nome' => 'Trabalhadores polivalentes da confecção de calçados']);
        Profissao::create(['id' => '7641', 'nome' => 'Trabalhadores da preparação da confecção de calçados']);
        Profissao::create(['id' => '7642', 'nome' => 'Operadores de máquinas de costurar e montar calçados']);
        Profissao::create(['id' => '7643', 'nome' => 'Trabalhadores de acabamento de calçados']);
        Profissao::create(['id' => '7650', 'nome' => 'Trabalhadores polivalentes da confecção de artefatos de tecidos e couros']);
        Profissao::create(['id' => '7651', 'nome' => 'Trabalhadores da preparação de artefatos de tecidos, couros e tapeçaria']);
        Profissao::create(['id' => '7652', 'nome' => 'Trabalhadores da confecção de artefatos de tecidos, couros e sintéticos']);
        Profissao::create(['id' => '7653', 'nome' => 'Operadores de máquinas na confecção de artefatos de  couro']);
        Profissao::create(['id' => '7654', 'nome' => 'Trabalhadores do acabamento de artefatos de tecidos e couros']);
        Profissao::create(['id' => '7661', 'nome' => 'Trabalhadores da pré-impressão gráfica']);
        Profissao::create(['id' => '7662', 'nome' => 'Trabalhadores da impressão gráfica']);
        Profissao::create(['id' => '7663', 'nome' => 'Trabalhadores do acabamento gráfico']);
        Profissao::create(['id' => '7664', 'nome' => 'Trabalhadores de laboratório fotográfico e radiológico']);
        Profissao::create(['id' => '7681', 'nome' => 'Trabalhadores de tecelagem manual, tricô, crochê, rendas e afins']);
        Profissao::create(['id' => '7682', 'nome' => 'Trabalhadores artesanais da confecção de peças e tecidos']);
        Profissao::create(['id' => '7683', 'nome' => 'Trabalhadores artesanais da confecção de calçados e artefatos de couros e peles']);
        Profissao::create(['id' => '7686', 'nome' => 'Trabalhadores tipográficos linotipistas e afins']);
        Profissao::create(['id' => '7687', 'nome' => 'Encadernadores e recuperadores de livros (pequenos lotes ou a unidade)']);
        Profissao::create(['id' => '7701', 'nome' => 'Supervisores em indústria de madeira, mobiliário e da carpintaria veicular']);
        Profissao::create(['id' => '7711', 'nome' => 'Marceneiros e afins']);
        Profissao::create(['id' => '7721', 'nome' => 'Trabalhadores de tratamento e preparação da madeira']);
        Profissao::create(['id' => '7731', 'nome' => 'Operadores de máquinas de desdobramento da madeira']);
        Profissao::create(['id' => '7732', 'nome' => 'Operadores de máquinas de aglomeração e prensagem de chapas']);
        Profissao::create(['id' => '7733', 'nome' => 'Operadores de usinagem convencional de madeira']);
        Profissao::create(['id' => '7734', 'nome' => 'Operadores de máquina de usinar madeira (produção em série)']);
        Profissao::create(['id' => '7735', 'nome' => 'Operadores de máquinas de usinagem de madeira cnc']);
        Profissao::create(['id' => '7741', 'nome' => 'Montadores de móveis e artefatos de madeira']);
        Profissao::create(['id' => '7751', 'nome' => 'Trabalhadores de arte e  do acabamento em madeira do mobiliário']);
        Profissao::create(['id' => '7764', 'nome' => 'Confeccionadores de artefatos de madeira, móveis de vime e afins']);
        Profissao::create(['id' => '7771', 'nome' => 'Carpinteiros navais']);
        Profissao::create(['id' => '7772', 'nome' => 'Carpinteiros de carrocerias e carretas']);
        Profissao::create(['id' => '7801', 'nome' => 'Supervisores de trabalhadores de embalagem e etiquetagem']);
        Profissao::create(['id' => '7811', 'nome' => 'Condutores de processos robotizados']);
        Profissao::create(['id' => '7813', 'nome' => 'Operadores de veículos subaquáticos controlados remotamente']);
        Profissao::create(['id' => '7817', 'nome' => 'Trabalhadores subaquáticos']);
        Profissao::create(['id' => '7821', 'nome' => 'Operadores de máquinas e equipamentos de elevação']);
        Profissao::create(['id' => '7822', 'nome' => 'Operadores de equipamentos de movimentação de cargas']);
        Profissao::create(['id' => '7823', 'nome' => 'Motoristas de veículos de pequeno e médio porte']);
        Profissao::create(['id' => '7824', 'nome' => 'Motoristas de ônibus urbanos, metropolitanos e rodoviários']);
        Profissao::create(['id' => '7825', 'nome' => 'Motoristas de veículos de cargas em geral']);
        Profissao::create(['id' => '7826', 'nome' => 'Operadores de veículos sobre trilhos e cabos aéreos']);
        Profissao::create(['id' => '7827', 'nome' => 'Trabalhadores aquaviários']);
        Profissao::create(['id' => '7828', 'nome' => 'Condutores de animais e de veículos de tração animal e pedais']);
        Profissao::create(['id' => '7831', 'nome' => 'Trabalhadores de manobras de transportes sobre trilhos']);
        Profissao::create(['id' => '7832', 'nome' => 'Trabalhadores de cargas e descargas de mercadorias']);
        Profissao::create(['id' => '7841', 'nome' => 'Trabalhadores de embalagem e de etiquetagem']);
        Profissao::create(['id' => '7842', 'nome' => 'Alimentadores de linhas de produção']);
        Profissao::create(['id' => '7911', 'nome' => 'Artesãos']);
        Profissao::create(['id' => '8101', 'nome' => 'Supervisores de produção em indústrias químicas, petroquímicas e afins']);
        Profissao::create(['id' => '8102', 'nome' => 'Supervisores de produção em indústrias de transformação de plásticos e borrachas']);
        Profissao::create(['id' => '8103', 'nome' => 'Supervisores de produção em indústrias de produtos farmacêuticos, cosméticos e afins']);
        Profissao::create(['id' => '8110', 'nome' => 'Operadores polivalentes de equipamentos em indústrias químicas, petroquímicas e afins']);
        Profissao::create(['id' => '8111', 'nome' => 'Operadores de equipamentos de moagem e mistura de materiais (tratamentos químicos e afins)']);
        Profissao::create(['id' => '8112', 'nome' => 'Operadores de calcinação e de tratamentos químicos de materiais radioativos']);
        Profissao::create(['id' => '8113', 'nome' => 'Operadores de equipamentos de filtragem e separação']);
        Profissao::create(['id' => '8114', 'nome' => 'Operadores de equipamentos de destilação, evaporação e reação']);
        Profissao::create(['id' => '8115', 'nome' => 'Operadores de equipamentos de produção e refino de petróleo e gás']);
        Profissao::create(['id' => '8116', 'nome' => 'Operadores de equipamentos de coqueificação']);
        Profissao::create(['id' => '8117', 'nome' => 'Operadores de instalações e máquinas de produtos plásticos, de borracha e moldadores de parafinas']);
        Profissao::create(['id' => '8118', 'nome' => 'Operadores de máquinas e instalações de produtos farmacêuticos, cosméticos e afins']);
        Profissao::create(['id' => '8121', 'nome' => 'Trabalhadores da fabricação de munição e explosivos químicos']);
        Profissao::create(['id' => '8131', 'nome' => 'Operadores de processos das indústrias de transformação de produtos químicos, petroquímicos e afins']);
        Profissao::create(['id' => '8181', 'nome' => 'Laboratoristas industriais auxiliares']);
        Profissao::create(['id' => '8201', 'nome' => 'Supervisores de produção em indústrias siderúrgicas']);
        Profissao::create(['id' => '8202', 'nome' => 'Supervisores na fabricação de materiais para construção (vidros e cerâmicas)']);
        Profissao::create(['id' => '8211', 'nome' => 'Operadores de instalações de sinterização']);
        Profissao::create(['id' => '8212', 'nome' => 'Operadores de fornos de primeira  fusão e aciaria']);
        Profissao::create(['id' => '8213', 'nome' => 'Operadores de equipamentos de laminação']);
        Profissao::create(['id' => '8214', 'nome' => 'Operadores de equipamentos de acabamento de chapas e metais']);
        Profissao::create(['id' => '8221', 'nome' => 'Forneiros metalúrgicos (segunda fusão e reaquecimento)']);
        Profissao::create(['id' => '8231', 'nome' => 'Operadores na preparação de massas para abrasivo, vidro, cerâmica, porcelana e materiais de construção']);
        Profissao::create(['id' => '8232', 'nome' => 'Operadores de equipamentos de fabricação  e beneficiamento de cristais, vidros, cerâmicas, porcelanas, fibras de vidro, abrasivos e afins']);
        Profissao::create(['id' => '8233', 'nome' => 'Operadores de instalações e equipamentos de fabricação de materiais de construção']);
        Profissao::create(['id' => '8281', 'nome' => 'Trabalhadores da fabricação de cerâmica estrutural para construção']);
        Profissao::create(['id' => '8301', 'nome' => 'Supervisores da fabricação de celulose e papel']);
        Profissao::create(['id' => '8311', 'nome' => 'Preparadores de pasta para fabricação de papel']);
        Profissao::create(['id' => '8321', 'nome' => 'Operadores de máquinas de fabricar papel e papelão']);
        Profissao::create(['id' => '8331', 'nome' => 'Operadores de máquinas na fabricação de produtos de papel e papelão']);
        Profissao::create(['id' => '8332', 'nome' => 'Trabalhadores artesanais de produtos de papel e papelão']);
        Profissao::create(['id' => '8401', 'nome' => 'Supervisores da fabricação de alimentos, bebidas e fumo']);
        Profissao::create(['id' => '8411', 'nome' => 'Trabalhadores da indústria de beneficiamento de grãos, cereais e afins']);
        Profissao::create(['id' => '8412', 'nome' => 'Trabalhadores no beneficiamento do sal']);
        Profissao::create(['id' => '8413', 'nome' => 'Trabalhadores na fabricação e refino de açúcar']);
        Profissao::create(['id' => '8414', 'nome' => 'Trabalhadores na fabricação e conservação de alimentos']);
        Profissao::create(['id' => '8415', 'nome' => 'Trabalhadores na pasteurização do leite e na fabricação de laticínios  e afins']);
        Profissao::create(['id' => '8416', 'nome' => 'Trabalhadores na industrialização de café, cacau, mate e de produtos afins']);
        Profissao::create(['id' => '8417', 'nome' => 'Trabalhadores na fabricação de cachaça, cerveja, vinhos e outras bebidas']);
        Profissao::create(['id' => '8418', 'nome' => 'Operadores de equipamentos na fabricação de pães, massas alimentícias, doces, chocolates e achocolatados']);
        Profissao::create(['id' => '8421', 'nome' => 'Cigarreiros e beneficiadores de fumo']);
        Profissao::create(['id' => '8422', 'nome' => 'Charuteiros']);
        Profissao::create(['id' => '8423', 'nome' => 'Cigarreiros']);
        Profissao::create(['id' => '8481', 'nome' => 'Trabalhadores artesanais na conservação de alimentos']);
        Profissao::create(['id' => '8482', 'nome' => 'Trabalhadores artesanais na pasteurização do leite e na fabricação de laticínios e afins']);
        Profissao::create(['id' => '8483', 'nome' => 'Padeiros, confeiteiros e afins']);
        Profissao::create(['id' => '8484', 'nome' => 'Trabalhadores na degustação e classificação de grãos e afins']);
        Profissao::create(['id' => '8485', 'nome' => 'Magarefes e afins']);
        Profissao::create(['id' => '8486', 'nome' => 'Trabalhadores artesanais na indústria do fumo']);
        Profissao::create(['id' => '8601', 'nome' => 'Supervisores da produção de utilidades']);
        Profissao::create(['id' => '8611', 'nome' => 'Operadores de instalações de geração e distribuição de energia elétrica, hidráulica, térmica ou nuclear']);
        Profissao::create(['id' => '8612', 'nome' => 'Operadores de instalações de distribuição de energia elétrica']);
        Profissao::create(['id' => '8621', 'nome' => 'Operadores de máquinas a vapor e utilidades']);
        Profissao::create(['id' => '8622', 'nome' => 'Operadores de instalações de captação, tratamento e distribuição de água']);
        Profissao::create(['id' => '8623', 'nome' => 'Operadores de instalações de captação e esgotos']);
        Profissao::create(['id' => '8624', 'nome' => 'Operadores de instalações de extração, processamento, envasamento e distribuição de gases']);
        Profissao::create(['id' => '8625', 'nome' => 'Operadores de instalações de refrigeração e ar-condicionado']);
        Profissao::create(['id' => '9101', 'nome' => 'Supervisores em serviços de reparação e manutenção de máquinas e equipamentos industriais, comerciais e residenciais']);
        Profissao::create(['id' => '9102', 'nome' => 'Supervisores em serviços de reparação e manutenção veicular']);
        Profissao::create(['id' => '9109', 'nome' => 'Supervisores de outros trabalhadores de serviços de reparação, conservação e manutenção']);
        Profissao::create(['id' => '9111', 'nome' => 'Mecânicos de manutenção de bombas, motores, compressores e equipamentos de transmissão']);
        Profissao::create(['id' => '9112', 'nome' => 'Mecânicos de manutenção e instalação de aparelhos de  climatização e refrigeração']);
        Profissao::create(['id' => '9113', 'nome' => 'Mecânicos de manutenção de máquinas industriais']);
        Profissao::create(['id' => '9131', 'nome' => 'Mecânicos de manutenção de máquinas pesadas e equipamentos agrícolas']);
        Profissao::create(['id' => '9141', 'nome' => 'Mecânicos de manutenção aeronáutica']);
        Profissao::create(['id' => '9142', 'nome' => 'Mecânicos de manutenção de motores e equipamentos navais']);
        Profissao::create(['id' => '9143', 'nome' => 'Mecânicos de manutenção metroferroviária']);
        Profissao::create(['id' => '9144', 'nome' => 'Mecânicos de manutenção de veículos automotores']);
        Profissao::create(['id' => '9151', 'nome' => 'Técnicos em manutenção e reparação de instrumentos de medição e precisão']);
        Profissao::create(['id' => '9152', 'nome' => 'Restauradores de instrumentos musicais']);
        Profissao::create(['id' => '9153', 'nome' => 'Técnicos em manutenção e reparação de equipamentos biomédicos']);
        Profissao::create(['id' => '9154', 'nome' => 'Reparadores de equipamentos fotográficos']);
        Profissao::create(['id' => '9191', 'nome' => 'Lubrificadores']);
        Profissao::create(['id' => '9192', 'nome' => 'Trabalhadores de manutenção de roçadeiras, motoserras e similares']);
        Profissao::create(['id' => '9193', 'nome' => 'Mecânicos de manutenção de bicicletas e equipamentos esportivos e de ginástica']);
        Profissao::create(['id' => '9501', 'nome' => 'Supervisores de manutenção eletroeletrônica industrial, comercial e predial']);
        Profissao::create(['id' => '9502', 'nome' => 'Supervisores de manutenção eletroeletrônica veicular']);
        Profissao::create(['id' => '9503', 'nome' => 'Supervisores de manutenção eletromecânica']);
        Profissao::create(['id' => '9511', 'nome' => 'Eletricistas de manutenção eletroeletrônica']);
        Profissao::create(['id' => '9513', 'nome' => 'Instaladores e mantenedores de sistemas eletroeletrônicos de segurança']);
        Profissao::create(['id' => '9531', 'nome' => 'Eletricistas eletrônicos de manutenção veicular (aérea, terrestre e naval)']);
        Profissao::create(['id' => '9541', 'nome' => 'Instaladores e mantenedores eletromecânicos de elevadores, escadas e portas automáticas']);
        Profissao::create(['id' => '9542', 'nome' => 'Reparadores de aparelhos eletrodomésticos']);
        Profissao::create(['id' => '9543', 'nome' => 'Reparadores de equipamentos de escritório']);
        Profissao::create(['id' => '9911', 'nome' => 'Conservadores de vias permanentes (trilhos)']);
        Profissao::create(['id' => '9912', 'nome' => 'Mantenedores de equipamentos de parques de diversões e similares']);
        Profissao::create(['id' => '9913', 'nome' => 'Reparadores de carrocerias de veículos']);
        Profissao::create(['id' => '9914', 'nome' => 'Mantenedores de edificações']);
        Profissao::create(['id' => '9921', 'nome' => 'Trabalhadores elementares de serviços de manutenção veicular']);
        Profissao::create(['id' => '9922', 'nome' => 'Trabalhadores operacionais de conservação de vias permanentes (exceto trilhos)']);

    }
}
